### PR TITLE
Feature/add support to podinfo 3.1.5

### PR DESCRIPTION
**Pull request by sebastianortizs4n**
Added changes from podinfo 3.1.5 to the helm-operator-getting-started.

### CODE REVIEW

**Review by stefanprodan — CHANGES_REQUESTED** [review]
Since the chart values.yaml format changed to:
```yaml
image:
  repository: stefanprodan/podinfo
  tag: 3.1.5
```

You have to update all the HelmRelease YAMLs in `/releases` and in the readme like so:
```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:fluxcd/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: dev-hdtwcel9
    replicaCount: 1
    hpa:
      enabled: false
```

**Comment by sebastianortizs4n** [comment]
Thank you @stefanprodan, I forgot to do that in the PR branch.

**Comment by stefanprodan** [comment]
The readme has YAMLs snippets with the old format, please update those as well.

**Comment by sebastianortizs4n** [comment]
My bad... it's done now.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @sebastianortizs4n

**Pull request merged**
